### ISSUE TITLE
Strange text selection on IE 11

### ISSUE THREAD

**Issue by sikorskl** [michaelmalonenz/aurelia-dragula#18]
Issue can be reproduced on code from https://github.com/michaelmalonenz/aurelia-dragula-example.

Steps to reproduce:
1. Open http://localhost:9000/#/multiarray on IE 11 
2. Drag element (e.g 1 from array A)
3. Start dragging
4. Text is selected all over the page.
5. Even when you drop item cursor is still active and select text. You have to click again to disable that.

On chrome it works fine.

Thanks for solving that

**Comment by doeck** [comment]
I'm running into the same issue in my project where I'm using dragula in an aurelia-dialog modal.
While dragging, text is highlighted in the background.

**Comment by doeck** [comment]
Found a solution that works for me: I'm adding -ms-user-select: none to the handle (the one I use to move around my row) and nothing gets selected anymore.
I also noticed that the selected issue only happens when I clicked on text. I'm dragging table rows with input elements. Clicking on inputs or spaces in between the inputs or the text did not select anything while dragging.
