### ISSUE TITLE
Does not work without Custom Element

### ISSUE THREAD

**Issue by TomFoyster** [michaelmalonenz/aurelia-dragula#27]
I've got this plugin working using your `<dragula-and-drop>` custom element, however I want to more specifically control what items are dragabble by using the `isContainer` option. 

Unfortunately though I cannot get the plugin to work using the following setup;

```
let options = new Options();
    options.isContainer = function (el) {
      return el.classList.contains('program-link');
    };
let dragula = new Dragula(containers, options);
```

**Comment by michaelmalonenz** [comment]
`isContainer` is bindable to the custom element, like so:

```html
<dragula-and-drop is-container.call="myIsContainerFn(el)"></dragula-and-drop
```

If defined, this will override the classes given by `targetClass` and `sourceClass` / or the defaults.

Other than that, the configuration defaults that apply to the custom element, don't necessarily apply to the manual method - you haven't done enough to detect that an item itself is draggable.  Getting the manual method working is non-trivial, which is why I created the custom element and gave it sensible defaults (and access to most extension points).

**Comment by michaelmalonenz** [comment]
closing due to lack of interest
