### ISSUE TITLE
Tiny example

### ISSUE THREAD

**Issue by Zoney** [michaelmalonenz/aurelia-dragula#3]
Thanks for an awesome plugin for Aurelia! Could we get a tiny example on how to use it?

To make sure we use it as intended.

**Comment by michaelmalonenz** [comment]
Yes - absolutely.  I even have the example application I want to write in mind, and I'll do it as soon as I have time

Meanwhile, here is an example: https://github.com/michaelmalonenz/skeleton-navigation/blob/playground/src/board/draganddrop.js

Though that's more of a replacement for how I was using the upstream library and doesn't show the aurelia-y way I have also included.

**Comment by michaelmalonenz** [comment]
Ok, I have found the time (thanks in no small part to religious holidays I don't observe, but still get time off for) to create this:
https://github.com/michaelmalonenz/aurelia-dragula-example

I have put it in a separate repository, because I want it to be separately licensed, meaning you are much free-er to do what you want with it, even using it as-is without unnecessary complications.

I shall be documenting the dragula-and-drop customElement soon.
