### ISSUE TITLE
What is itemVM and siblingVM is for?

### ISSUE THREAD

**Issue by tatva-nisarg** [michaelmalonenz/aurelia-dragula#37]
I am always getting this null

**Comment by michaelmalonenz** [comment]
Can you give a bit more context?  I assume this is on the `drop` event, but are you using the custom element?

In general, however, the parameters which have the `VM` suffix, are the View Model of an element involved in the callback iff that element represents an aurelia component / custom element.

If you have (entire, not the "inner" html) aurelia components as the elements being dropped, and are not getting the View Model passed with it, then it's probably because I use an undocumented API to retrieve said ViewModels and aurelia might have changed under me (as is their right).  If that's the case, then I look forward to a PR which solves this problem, as I am on leave at the moment.

Thanks for your interest in the plugin!
